### ISSUE TITLE
Overlapping using grids

### ISSUE THREAD

**Issue by Riv67** [Riv67/components-on-a-grid#1]
@JessJodoin @hellachella

I’m having trouble with the grid for the header (trying to overlap the h1 and nav on the banner image). I can seem to make the banner image bigger to fill the space. I put display:grid on my header, and then added 
header img {
  grid column: 1 / -1;
  grid-row: 1 / -1;
}
I’m also not sure if my numbers and fraction for the grid are right. I’ve tried using the cheat sheets and video. Help!

**Comment by JessJodoin** [comment]
You're header should only be `display: contents`, I'd put the grid on the body so everything can be more easily placed on the grid and add `display: contents` to the main.

For your grid, `grid-template-rows` isn't super necessary, we can just let the browser do the work for us. And both of the columns should be 1fr

**Comment by JessJodoin** [comment]
Also you can definitely DM me on slack if you want more help 😄
